#!/usr/bin/env bash

set -eou pipefail

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

nj=16
stage=${STAGE:--1}
stop_stage=${STOP_STAGE:-3}

# Defualt values for TTS
prep_tts=1
control_tts=1
atypical_tts=0
suffix="jsonl.gz"

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/LJSpeech-1.1

dl_dir=$PWD/download

audio_extractor="Encodec"  # or Fbank
audio_feats_dir=data/tokenized

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --stage)
      stage=$2
      shift 2
      ;;
    --stop-stage)
      stop_stage=$2
      shift 2
      ;;
    --prep-tts)
      prep_tts=$2
      shift 2
      ;;
    --control-tts)
      control_tts=$2
      shift 2
      ;;
    --atypical-tts)
      atypical_tts=$2
      shift 2
      ;;
    --suffix)
      suffix=$2
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# . shared/parse_options.sh || exit 1

# Determine dataset parts based on prep-tts
if [[ $prep_tts -eq 1 ]]; then
  dataset_parts="uaspeech_tts"
else
  dataset_parts="uaspeech_vc"
fi

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

# if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
#   log "Stage 0: Download data"

#   # If you have pre-downloaded it to /path/to/LJSpeech,
#   # you can create a symlink
#   #
#   ln -sfv /home/data1/VallE/vall-e/egs/uaspeech $dl_dir/UASpeech
#   #
#   # if [ ! -d $dl_dir/LJSpeech-1.1 ];then
#   #   lhotse download UASpeech $dl_dir
#   # fi
# fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare UASpeech manifest"
  # We assume that you have downloaded the UASpeech corpus
  # to $dl_dir/LJSpeech
  mkdir -p data/manifests
  if [ ! -e data/manifests/.uaspeech.done ]; then
    # If lhotse has the prepare_uaspeech in its library try line below
    # lhotse prepare uaspeech $dl_dir/UASpeech data/manifests
    # cluster (wherever UASpeech is mounted): /scratch/lewis.jor/UASpeech
    # polaris: /home/data1/data/UASpeech
    python uaspeech.py --uaspeech-path /scratch/lewis.jor/UASpeech \
          --prep-tts $prep_tts --control-tts $control_tts \
          --atypical-tts $atypical_tts --output-dir data/manifests
    touch data/manifests/.uaspeech.done
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 3: ${audio_extractor} UASpeech"

  mkdir -p ${audio_feats_dir}
  if [ ! -e ${audio_feats_dir}/.uaspeech.done ]; then
    python3 bin/tokenizer.py --dataset-parts "$dataset_parts" --prefix "uaspeech" --suffix "jsonl.gz"\
        --audio-extractor ${audio_extractor} \
        --batch-duration 400 \
        --concat-speakers 0\
        --tts $prep_tts\
        --src-dir "data/manifests" \
        --output-dir "${audio_feats_dir}"
  fi

  touch ${audio_feats_dir}/.uaspeech.done

fi

python3 ./bin/display_manifest_statistics.py --manifest-dir ${audio_feats_dir}